In [2]:
import pandas as pd

In [3]:
df11 = pd.read_csv("bulk (2).csv")

In [4]:
df21 = pd.read_csv("census2021-ts007-utla (Age).csv")

In [5]:
df11.shape

(174, 106)

In [6]:
df11.head(5)

,date,geography,geography code,Rural Urban,Age: All categories: Age; measures: Value,Age: Age under 1; measures: Value,Age: Age 1; measures: Value,Age: Age 2; measures: Value,Age: Age 3; measures: Value,Age: Age 4; measures: Value,...,Age: Age 91; measures: Value,Age: Age 92; measures: Value,Age: Age 93; measures: Value,Age: Age 94; measures: Value,Age: Age 95; measures: Value,Age: Age 96; measures: Value,Age: Age 97; measures: Value,Age: Age 98; measures: Value,Age: Age 99; measures: Value,Age: Age 100 and over; measures: Value
0,2011,Darlington,E06000005,Total,105564,1344,1371,1302,1297,1265,...,148,104,91,69,50,34,26,32,22,28
1,2011,County Durham,E06000047,Total,513242,5884,5645,5602,5826,5617,...,709,461,331,262,215,187,144,87,76,80
2,2011,Hartlepool,E06000001,Total,92028,1097,1176,1155,1159,1111,...,127,63,51,34,29,15,16,15,6,14
3,2011,Middlesbrough,E06000002,Total,138412,1979,1965,1797,1863,1827,...,183,103,90,56,40,46,30,19,12,15
4,2011,Northumberland,E06000057,Total,316028,3148,3150,3205,3325,3175,...,517,377,231,242,183,140,72,62,53,81

In [7]:
df21.shape

(174, 116)

In [8]:
df21.head(5)

,date,geography,geography code,Age: Total; measures: Value,Age: Aged 4 years and under; measures: Value,Age: Aged under 1 year; measures: Value,Age: Aged 1 year; measures: Value,Age: Aged 2 years; measures: Value,Age: Aged 3 years; measures: Value,Age: Aged 4 years; measures: Value,...,Age: Aged 91 years; measures: Value,Age: Aged 92 years; measures: Value,Age: Aged 93 years; measures: Value,Age: Aged 94 years; measures: Value,Age: Aged 95 years; measures: Value,Age: Aged 96 years; measures: Value,Age: Aged 97 years; measures: Value,Age: Aged 98 years; measures: Value,Age: Aged 99 years; measures: Value,Age: Aged 100 years and over; measures: Value
0,2021,Darlington,E06000005,107807,5494,1040,1048,1109,1167,1130,...,178,137,105,104,73,53,20,38,25,22
1,2021,County Durham,E06000047,522062,24752,4623,4809,4969,4990,5361,...,834,633,446,369,284,235,127,92,62,87
2,2021,Hartlepool,E06000001,92334,4983,918,954,1046,988,1077,...,130,110,92,62,48,30,19,19,14,21
3,2021,Middlesbrough,E06000002,143922,8928,1621,1720,1766,1908,1913,...,217,153,112,82,61,47,38,18,15,22
4,2021,Northumberland,E06000057,320565,14235,2575,2631,2905,2985,3139,...,611,514,383,316,219,177,114,67,49,80

In [9]:
(df21[["geography code"]] == df11[["geography code"]])["geography code"].value_counts()

geography code
True     91
False    83
Name: count, dtype: int64

In [10]:
df21.head(5)

,date,geography,geography code,Age: Total; measures: Value,Age: Aged 4 years and under; measures: Value,Age: Aged under 1 year; measures: Value,Age: Aged 1 year; measures: Value,Age: Aged 2 years; measures: Value,Age: Aged 3 years; measures: Value,Age: Aged 4 years; measures: Value,...,Age: Aged 91 years; measures: Value,Age: Aged 92 years; measures: Value,Age: Aged 93 years; measures: Value,Age: Aged 94 years; measures: Value,Age: Aged 95 years; measures: Value,Age: Aged 96 years; measures: Value,Age: Aged 97 years; measures: Value,Age: Aged 98 years; measures: Value,Age: Aged 99 years; measures: Value,Age: Aged 100 years and over; measures: Value
0,2021,Darlington,E06000005,107807,5494,1040,1048,1109,1167,1130,...,178,137,105,104,73,53,20,38,25,22
1,2021,County Durham,E06000047,522062,24752,4623,4809,4969,4990,5361,...,834,633,446,369,284,235,127,92,62,87
2,2021,Hartlepool,E06000001,92334,4983,918,954,1046,988,1077,...,130,110,92,62,48,30,19,19,14,21
3,2021,Middlesbrough,E06000002,143922,8928,1621,1720,1766,1908,1913,...,217,153,112,82,61,47,38,18,15,22
4,2021,Northumberland,E06000057,320565,14235,2575,2631,2905,2985,3139,...,611,514,383,316,219,177,114,67,49,80

In [11]:
df21.columns.tolist()

['date',
 'geography',
 'geography code',
 'Age: Total; measures: Value',
 'Age: Aged 4 years and under; measures: Value',
 'Age: Aged under 1 year; measures: Value',
 'Age: Aged 1 year; measures: Value',
 'Age: Aged 2 years; measures: Value',
 'Age: Aged 3 years; measures: Value',
 'Age: Aged 4 years; measures: Value',
 'Age: Aged 5 to 9 years; measures: Value',
 'Age: Aged 5 years; measures: Value',
 'Age: Aged 6 years; measures: Value',
 'Age: Aged 7 years; measures: Value',
 'Age: Aged 8 years; measures: Value',
 'Age: Aged 9 years; measures: Value',
 'Age: Aged 10 to 15 years; measures: Value',
 'Age: Aged 10 years; measures: Value',
 'Age: Aged 11 years; measures: Value',
 'Age: Aged 12 years; measures: Value',
 'Age: Aged 13 years; measures: Value',
 'Age: Aged 14 years; measures: Value',
 'Age: Aged 15 years; measures: Value',
 'Age: Aged 16 to 19 years; measures: Value',
 'Age: Aged 16 years; measures: Value',
 'Age: Aged 17 years; measures: Value',
 'Age: Aged 18 years; measures: Value',
 'Age: Aged 19 years; measures: Value',
 'Age: Aged 20 to 24 years; measures: Value',
 'Age: Aged 20 years; measures: Value',
 'Age: Aged 21 years; measures: Value',
 'Age: Aged 22 years; measures: Value',
 'Age: Aged 23 years; measures: Value',
 'Age: Aged 24 years; measures: Value',
 'Age: Aged 25 to 34 years; measures: Value',
 'Age: Aged 25 years; measures: Value',
 'Age: Aged 26 years; measures: Value',
 'Age: Aged 27 years; measures: Value',
 'Age: Aged 28 years; measures: Value',
 'Age: Aged 29 years; measures: Value',
 'Age: Aged 30 years; measures: Value',
 'Age: Aged 31 years; measures: Value',
 'Age: Aged 32 years; measures: Value',
 'Age: Aged 33 years; measures: Value',
 'Age: Aged 34 years; measures: Value',
 'Age: Aged 35 to 49 years; measures: Value',
 'Age: Aged 35 years; measures: Value',
 'Age: Aged 36 years; measures: Value',
 'Age: Aged 37 years; measures: Value',
 'Age: Aged 38 years; measures: Value',
 'Age: Aged 39 years; measures: Value',
 'Age: Aged 40 years; measures: Value',
 'Age: Aged 41 years; measures: Value',
 'Age: Aged 42 years; measures: Value',
 'Age: Aged 43 years; measures: Value',
 'Age: Aged 44 years; measures: Value',
 'Age: Aged 45 years; measures: Value',
 'Age: Aged 46 years; measures: Value',
 'Age: Aged 47 years; measures: Value',
 'Age: Aged 48 years; measures: Value',
 'Age: Aged 49 years; measures: Value',
 'Age: Aged 50 to 64 years; measures: Value',
 'Age: Aged 50 years; measures: Value',
 'Age: Aged 51 years; measures: Value',
 'Age: Aged 52 years; measures: Value',
 'Age: Aged 53 years; measures: Value',
 'Age: Aged 54 years; measures: Value',
 'Age: Aged 55 years; measures: Value',
 'Age: Aged 56 years; measures: Value',
 'Age: Aged 57 years; measures: Value',
 'Age: Aged 58 years; measures: Value',
 'Age: Aged 59 years; measures: Value',
 'Age: Aged 60 years; measures: Value',
 'Age: Aged 61 years; measures: Value',
 'Age: Aged 62 years; measures: Value',
 'Age: Aged 63 years; measures: Value',
 'Age: Aged 64 years; measures: Value',
 'Age: Aged 65 to 74 years; measures: Value',
 'Age: Aged 65 years; measures: Value',
 'Age: Aged 66 years; measures: Value',
 'Age: Aged 67 years; measures: Value',
 'Age: Aged 68 years; measures: Value',
 'Age: Aged 69 years; measures: Value',
 'Age: Aged 70 years; measures: Value',
 'Age: Aged 71 years; measures: Value',
 'Age: Aged 72 years; measures: Value',
 'Age: Aged 73 years; measures: Value',
 'Age: Aged 74 years; measures: Value',
 'Age: Aged 75 to 84 years; measures: Value',
 'Age: Aged 75 years; measures: Value',
 'Age: Aged 76 years; measures: Value',
 'Age: Aged 77 years; measures: Value',
 'Age: Aged 78 years; measures: Value',
 'Age: Aged 79 years; measures: Value',
 'Age: Aged 80 years; measures: Value',
 'Age: Aged 81 years; measures: Value',
 'Age: Aged 82 years; measures: Value',
 'Age: Aged 83 years; measures: Value',
 'Age: Aged 84 years; measures: Value',
 'Age: Aged 85 years and over; measures: Value',
 'Age: Aged 85 years; measures: Value',
 'Age: Aged 86 years; measures: Value',
 'Age: Aged 87 years; measures: Value',
 'Age: Aged 88 years; measures: Value',
 'Age: Aged 89 years; measures: Value',
 'Age: Aged 90 years; measures: Value',
 'Age: Aged 91 years; measures: Value',
 'Age: Aged 92 years; measures: Value',
 'Age: Aged 93 years; measures: Value',
 'Age: Aged 94 years; measures: Value',
 'Age: Aged 95 years; measures: Value',
 'Age: Aged 96 years; measures: Value',
 'Age: Aged 97 years; measures: Value',
 'Age: Aged 98 years; measures: Value',
 'Age: Aged 99 years; measures: Value',
 'Age: Aged 100 years and over; measures: Value']

In [12]:
df11.columns.tolist()

['date',
 'geography',
 'geography code',
 'Rural Urban',
 'Age: All categories: Age; measures: Value',
 'Age: Age under 1; measures: Value',
 'Age: Age 1; measures: Value',
 'Age: Age 2; measures: Value',
 'Age: Age 3; measures: Value',
 'Age: Age 4; measures: Value',
 'Age: Age 5; measures: Value',
 'Age: Age 6; measures: Value',
 'Age: Age 7; measures: Value',
 'Age: Age 8; measures: Value',
 'Age: Age 9; measures: Value',
 'Age: Age 10; measures: Value',
 'Age: Age 11; measures: Value',
 'Age: Age 12; measures: Value',
 'Age: Age 13; measures: Value',
 'Age: Age 14; measures: Value',
 'Age: Age 15; measures: Value',
 'Age: Age 16; measures: Value',
 'Age: Age 17; measures: Value',
 'Age: Age 18; measures: Value',
 'Age: Age 19; measures: Value',
 'Age: Age 20; measures: Value',
 'Age: Age 21; measures: Value',
 'Age: Age 22; measures: Value',
 'Age: Age 23; measures: Value',
 'Age: Age 24; measures: Value',
 'Age: Age 25; measures: Value',
 'Age: Age 26; measures: Value',
 'Age: Age 27; measures: Value',
 'Age: Age 28; measures: Value',
 'Age: Age 29; measures: Value',
 'Age: Age 30; measures: Value',
 'Age: Age 31; measures: Value',
 'Age: Age 32; measures: Value',
 'Age: Age 33; measures: Value',
 'Age: Age 34; measures: Value',
 'Age: Age 35; measures: Value',
 'Age: Age 36; measures: Value',
 'Age: Age 37; measures: Value',
 'Age: Age 38; measures: Value',
 'Age: Age 39; measures: Value',
 'Age: Age 40; measures: Value',
 'Age: Age 41; measures: Value',
 'Age: Age 42; measures: Value',
 'Age: Age 43; measures: Value',
 'Age: Age 44; measures: Value',
 'Age: Age 45; measures: Value',
 'Age: Age 46; measures: Value',
 'Age: Age 47; measures: Value',
 'Age: Age 48; measures: Value',
 'Age: Age 49; measures: Value',
 'Age: Age 50; measures: Value',
 'Age: Age 51; measures: Value',
 'Age: Age 52; measures: Value',
 'Age: Age 53; measures: Value',
 'Age: Age 54; measures: Value',
 'Age: Age 55; measures: Value',
 'Age: Age 56; measures: Value',
 'Age: Age 57; measures: Value',
 'Age: Age 58; measures: Value',
 'Age: Age 59; measures: Value',
 'Age: Age 60; measures: Value',
 'Age: Age 61; measures: Value',
 'Age: Age 62; measures: Value',
 'Age: Age 63; measures: Value',
 'Age: Age 64; measures: Value',
 'Age: Age 65; measures: Value',
 'Age: Age 66; measures: Value',
 'Age: Age 67; measures: Value',
 'Age: Age 68; measures: Value',
 'Age: Age 69; measures: Value',
 'Age: Age 70; measures: Value',
 'Age: Age 71; measures: Value',
 'Age: Age 72; measures: Value',
 'Age: Age 73; measures: Value',
 'Age: Age 74; measures: Value',
 'Age: Age 75; measures: Value',
 'Age: Age 76; measures: Value',
 'Age: Age 77; measures: Value',
 'Age: Age 78; measures: Value',
 'Age: Age 79; measures: Value',
 'Age: Age 80; measures: Value',
 'Age: Age 81; measures: Value',
 'Age: Age 82; measures: Value',
 'Age: Age 83; measures: Value',
 'Age: Age 84; measures: Value',
 'Age: Age 85; measures: Value',
 'Age: Age 86; measures: Value',
 'Age: Age 87; measures: Value',
 'Age: Age 88; measures: Value',
 'Age: Age 89; measures: Value',
 'Age: Age 90; measures: Value',
 'Age: Age 91; measures: Value',
 'Age: Age 92; measures: Value',
 'Age: Age 93; measures: Value',
 'Age: Age 94; measures: Value',
 'Age: Age 95; measures: Value',
 'Age: Age 96; measures: Value',
 'Age: Age 97; measures: Value',
 'Age: Age 98; measures: Value',
 'Age: Age 99; measures: Value',
 'Age: Age 100 and over; measures: Value']

In [ ]:
df21 = df21.drop(["Age: Aged 4 years and under; measures: Value",
                  "Age: Aged 5 to 9 years; measures: Value", 
                  "Age: Aged 10 to 15 years; measures: Value", 
                  "Age: Aged 16 to 19 years; measures: Value", 
                  "Age: Aged 20 to 24 years; measures: Value",
                  "Age: Aged 25 to 34 years; measures: Value",
                  "Age: Aged 35 to 49 years; measures: Value",
                  "Age: Aged 50 to 64 years; measures: Value",
                  "Age: Aged 65 to 74 years; measures: Value",
                  "Age: Aged 75 to 84 years; measures: Value",
                  "Age: Aged 50 to 64 years; measures: Value",
                  "Age: Aged 85 years and over; measures: Value",
                  "date",
                  "Age: Total; measures: Value"], axis =1)

In [14]:
df21.columns = ["geography", 'geography code'] + [str(i) for i in range(0,100)] + ["100+"]

In [15]:
df21.columns.tolist()

['geography',
 'geography code',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '30',
 '31',
 '32',
 '33',
 '34',
 '35',
 '36',
 '37',
 '38',
 '39',
 '40',
 '41',
 '42',
 '43',
 '44',
 '45',
 '46',
 '47',
 '48',
 '49',
 '50',
 '51',
 '52',
 '53',
 '54',
 '55',
 '56',
 '57',
 '58',
 '59',
 '60',
 '61',
 '62',
 '63',
 '64',
 '65',
 '66',
 '67',
 '68',
 '69',
 '70',
 '71',
 '72',
 '73',
 '74',
 '75',
 '76',
 '77',
 '78',
 '79',
 '80',
 '81',
 '82',
 '83',
 '84',
 '85',
 '86',
 '87',
 '88',
 '89',
 '90',
 '91',
 '92',
 '93',
 '94',
 '95',
 '96',
 '97',
 '98',
 '99',
 '100+']

In [16]:
df11 = df11.drop(["date", "Rural Urban", 'Age: All categories: Age; measures: Value'], axis = 1)

In [17]:
df11.columns = ["geography", 'geography code'] + [str(i) for i in range(0,100)] + ["100+"]

In [18]:
df11.head(5)

,geography,geography code,0,1,2,3,4,5,6,7,...,91,92,93,94,95,96,97,98,99,100+
0,Darlington,E06000005,1344,1371,1302,1297,1265,1289,1271,1230,...,148,104,91,69,50,34,26,32,22,28
1,County Durham,E06000047,5884,5645,5602,5826,5617,5366,5325,5127,...,709,461,331,262,215,187,144,87,76,80
2,Hartlepool,E06000001,1097,1176,1155,1159,1111,1150,1051,1001,...,127,63,51,34,29,15,16,15,6,14
3,Middlesbrough,E06000002,1979,1965,1797,1863,1827,1835,1703,1640,...,183,103,90,56,40,46,30,19,12,15
4,Northumberland,E06000057,3148,3150,3205,3325,3175,3336,3207,3320,...,517,377,231,242,183,140,72,62,53,81

In [19]:
df11.iloc[:, 2:7].sum(axis =1)

0       6579
1      28574
2       5698
3       9431
4      16003
       ...
169    11313
170     4016
171     5381
172     4637
173     9543
Length: 174, dtype: int64

In [20]:
df11_bands = df11[["geography",	"geography code"]]

In [21]:
i = 2
for j in (range(0,100, 5)):
    st = f"{j}-{j+4}"
    
    df11_bands[st] = df11.iloc[:,i:i+5].sum(axis =1)
    i = i+5

In [22]:
df11_bands["100+"] = df11["100+"]

In [23]:
df11_bands.columns.to_list()

['geography',
 'geography code',
 '0-4',
 '5-9',
 '10-14',
 '15-19',
 '20-24',
 '25-29',
 '30-34',
 '35-39',
 '40-44',
 '45-49',
 '50-54',
 '55-59',
 '60-64',
 '65-69',
 '70-74',
 '75-79',
 '80-84',
 '85-89',
 '90-94',
 '95-99',
 '100+']

In [24]:
df21_bands = df21[["geography",	"geography code"]]

In [25]:
i = 2
for j in (range(0,100, 5)):
    st = f"{j}-{j+4}"
    
    df21_bands[st] = df21.iloc[:,i:i+5].sum(axis =1)
    i = i+5
    
df21_bands["100+"] = df21["100+"]

In [26]:
df21_bands.columns.to_list()

['geography',
 'geography code',
 '0-4',
 '5-9',
 '10-14',
 '15-19',
 '20-24',
 '25-29',
 '30-34',
 '35-39',
 '40-44',
 '45-49',
 '50-54',
 '55-59',
 '60-64',
 '65-69',
 '70-74',
 '75-79',
 '80-84',
 '85-89',
 '90-94',
 '95-99',
 '100+']

In [27]:
df21_bands.head(5)

,geography,geography code,0-4,5-9,10-14,15-19,20-24,25-29,30-34,35-39,...,55-59,60-64,65-69,70-74,75-79,80-84,85-89,90-94,95-99,100+
0,Darlington,E06000005,5494,6330,6626,5788,5426,6379,6968,6562,...,7855,7004,5959,5980,4150,3119,1841,765,209,22
1,County Durham,E06000047,24752,28357,29499,31231,33054,29206,30679,30620,...,39456,35125,31041,30716,21730,15059,8549,3355,800,87
2,Hartlepool,E06000001,4983,5582,5920,5180,5110,5495,5884,5463,...,7130,6295,5247,5084,3222,2463,1490,575,130,21
3,Middlesbrough,E06000002,8928,9795,9465,8571,10171,10322,10320,9375,...,9369,8720,7208,6462,4300,3236,1959,812,179,22
4,Northumberland,E06000057,14235,16686,17409,15678,13906,15924,16936,17408,...,25775,24758,22584,22975,15812,10593,6248,2631,626,80

In [28]:
df21_bands.columns.tolist()

['geography',
 'geography code',
 '0-4',
 '5-9',
 '10-14',
 '15-19',
 '20-24',
 '25-29',
 '30-34',
 '35-39',
 '40-44',
 '45-49',
 '50-54',
 '55-59',
 '60-64',
 '65-69',
 '70-74',
 '75-79',
 '80-84',
 '85-89',
 '90-94',
 '95-99',
 '100+']

In [29]:
df11_bands.head(5)

,geography,geography code,0-4,5-9,10-14,15-19,20-24,25-29,30-34,35-39,...,55-59,60-64,65-69,70-74,75-79,80-84,85-89,90-94,95-99,100+
0,Darlington,E06000005,6579,6074,6224,6408,6071,6607,6429,6847,...,6308,6685,5205,4512,3526,2646,1740,618,164,28
1,County Durham,E06000047,28574,25659,27869,33267,35155,30628,28133,30498,...,32950,35395,27874,23009,17850,12785,7321,2717,709,80
2,Hartlepool,E06000001,5698,5192,5653,6278,5955,5622,5033,5373,...,5595,5837,4236,3938,3327,2241,1323,438,81,14
3,Middlesbrough,E06000002,9431,8276,8485,10064,11690,9765,8295,8135,...,7933,7531,5680,5153,4278,3115,1658,645,147,15
4,Northumberland,E06000057,16003,16345,17677,18464,16224,16187,16121,17907,...,22172,24533,19062,15304,12249,8769,5233,2096,510,81

In [30]:
df11_bands.columns = ['geography',
 'geography code',
 '[0-4]',
 '[5-9]',
 '[10-14]',
 '[15-19]',
 '[20-24]',
 '[25-29]',
 '[30-34]',
 '[35-39]',
 '[40-44]',
 '[45-49]',
 '[50-54]',
 '[55-59]',
 '[60-64]',
 '[65-69]',
 '[70-74]',
 '[75-79]',
 '[80-84]',
 '[85-89]',
 '[90-94]',
 '[95-99]',
 '[100+]']

In [31]:
merged_df = df21_bands.merge(df11_bands, on="geography code", how = "inner")

In [32]:
merged_df.head(5)

,geography_x,geography code,0-4,5-9,10-14,15-19,20-24,25-29,30-34,35-39,...,[55-59],[60-64],[65-69],[70-74],[75-79],[80-84],[85-89],[90-94],[95-99],[100+]
0,Darlington,E06000005,5494,6330,6626,5788,5426,6379,6968,6562,...,6308,6685,5205,4512,3526,2646,1740,618,164,28
1,County Durham,E06000047,24752,28357,29499,31231,33054,29206,30679,30620,...,32950,35395,27874,23009,17850,12785,7321,2717,709,80
2,Hartlepool,E06000001,4983,5582,5920,5180,5110,5495,5884,5463,...,5595,5837,4236,3938,3327,2241,1323,438,81,14
3,Middlesbrough,E06000002,8928,9795,9465,8571,10171,10322,10320,9375,...,7933,7531,5680,5153,4278,3115,1658,645,147,15
4,Northumberland,E06000057,14235,16686,17409,15678,13906,15924,16936,17408,...,22172,24533,19062,15304,12249,8769,5233,2096,510,81

In [33]:
df_2021 = merged_df[['geography_x',
 'geography code',
 '0-4',
 '5-9',
 '10-14',
 '15-19',
 '20-24',
 '25-29',
 '30-34',
 '35-39',
 '40-44',
 '45-49',
 '50-54',
 '55-59',
 '60-64',
 '65-69',
 '70-74',
 '75-79',
 '80-84',
 '85-89',
 '90-94',
 '95-99',
 '100+']]

In [34]:
df_2011 = merged_df[['geography_x',
 'geography code',
 '[0-4]',
 '[5-9]',
 '[10-14]',
 '[15-19]',
 '[20-24]',
 '[25-29]',
 '[30-34]',
 '[35-39]',
 '[40-44]',
 '[45-49]',
 '[50-54]',
 '[55-59]',
 '[60-64]',
 '[65-69]',
 '[70-74]',
 '[75-79]',
 '[80-84]',
 '[85-89]',
 '[90-94]',
 '[95-99]',
 '[100+]']]

In [35]:
df_2011.columns = ['geography_x',
 'geography code',
 '0-4',
 '5-9',
 '10-14',
 '15-19',
 '20-24',
 '25-29',
 '30-34',
 '35-39',
 '40-44',
 '45-49',
 '50-54',
 '55-59',
 '60-64',
 '65-69',
 '70-74',
 '75-79',
 '80-84',
 '85-89',
 '90-94',
 '95-99',
 '100+']

In [36]:
df_2011.shape

(169, 23)

In [37]:
df_2021.shape

(169, 23)

In [38]:
df_2021["Year"] = 2021
df_2011["Year"] = 2011

In [39]:
df_combined = pd.concat([df_2011, df_2021], ignore_index=True)
id_vars = ["geography_x", "geography code", "Year"]
age_columns = [col for col in df_combined.columns if col not in id_vars]
df_long = df_combined.melt(id_vars = id_vars, value_vars=age_columns, var_name="Age_Bin", value_name="Population")
age_map = {name:i for i , name in enumerate(age_columns)}
df_long["Age_Index"] = df_long["Age_Bin"].map(age_map)
df_long["Year_Index"] = df_long["Year"].map({2011:0, 2021:1})
df_long["Cohort_Index"] = (2 * df_long["Year_Index"]) - df_long["Age_Index"]
df_long["Cohort_Index"] -= df_long["Cohort_Index"].min()
print("Data successfully reshaped for modelling")

Data successfully reshaped for modelling

In [ ]:
df_long

,geography_x,geography code,Year,Age_Bin,Population,Age_Index,Year_Index,Cohort_Index
0,Darlington,E06000005,2011,0-4,6579,0,0,20
1,County Durham,E06000047,2011,0-4,28574,0,0,20
2,Hartlepool,E06000001,2011,0-4,5698,0,0,20
3,Middlesbrough,E06000002,2011,0-4,9431,0,0,20
4,Northumberland,E06000057,2011,0-4,16003,0,0,20

In [41]:
df_long.shape

(7098, 8)

In [42]:
!pip install pymc pytensor

Requirement already satisfied: pymc in c:\Users\Aman Kumar Singh\anaconda3\envs\ats\Lib\site-packages (5.28.4)
Requirement already satisfied: pytensor in c:\Users\Aman Kumar Singh\anaconda3\envs\ats\Lib\site-packages (2.38.2)
Requirement already satisfied: arviz<1.0,>=0.13.0 in c:\Users\Aman Kumar Singh\anaconda3\envs\ats\Lib\site-packages (from pymc) (0.23.4)
Requirement already satisfied: cachetools<7,>=4.2.1 in c:\Users\Aman Kumar Singh\anaconda3\envs\ats\Lib\site-packages (from pymc) (6.2.6)
Requirement already satisfied: cloudpickle in c:\Users\Aman Kumar Singh\anaconda3\envs\ats\Lib\site-packages (from pymc) (3.1.2)
Requirement already satisfied: numpy>=1.25.0 in c:\Users\Aman Kumar Singh\anaconda3\envs\ats\Lib\site-packages (from pymc) (2.4.3)
Requirement already satisfied: pandas>=0.24.0 in c:\Users\Aman Kumar Singh\anaconda3\envs\ats\Lib\site-packages (from pymc) (3.0.1)
Requirement already satisfied: rich>=13.7.1 in c:\Users\Aman Kumar Singh\anaconda3\envs\ats\Lib\site-packages (from pymc) (14.3.3)
Requirement already satisfied: scipy>=1.4.1 in c:\Users\Aman Kumar Singh\anaconda3\envs\ats\Lib\site-packages (from pymc) (1.17.1)
Requirement already satisfied: threadpoolctl<4.0.0,>=3.1.0 in c:\Users\Aman Kumar Singh\anaconda3\envs\ats\Lib\site-packages (from pymc) (3.6.0)
Requirement already satisfied: typing-extensions>=3.7.4 in c:\Users\Aman Kumar Singh\anaconda3\envs\ats\Lib\site-packages (from pymc) (4.15.0)
Requirement already satisfied: setuptools>=59.0.0 in c:\Users\Aman Kumar Singh\anaconda3\envs\ats\Lib\site-packages (from pytensor) (82.0.1)
Requirement already satisfied: numba<1,>0.57 in c:\Users\Aman Kumar Singh\anaconda3\envs\ats\Lib\site-packages (from pytensor) (0.64.0)
Requirement already satisfied: filelock>=3.15 in c:\Users\Aman Kumar Singh\anaconda3\envs\ats\Lib\site-packages (from pytensor) (3.25.2)
Requirement already satisfied: etuples in c:\Users\Aman Kumar Singh\anaconda3\envs\ats\Lib\site-packages (from pytensor) (0.3.10)
Requirement already satisfied: logical-unification in c:\Users\Aman Kumar Singh\anaconda3\envs\ats\Lib\site-packages (from pytensor) (0.4.7)
Requirement already satisfied: miniKanren in c:\Users\Aman Kumar Singh\anaconda3\envs\ats\Lib\site-packages (from pytensor) (1.0.5)
Requirement already satisfied: cons in c:\Users\Aman Kumar Singh\anaconda3\envs\ats\Lib\site-packages (from pytensor) (0.4.7)
Requirement already satisfied: matplotlib>=3.8 in c:\Users\Aman Kumar Singh\anaconda3\envs\ats\Lib\site-packages (from arviz<1.0,>=0.13.0->pymc) (3.10.8)
Requirement already satisfied: packaging in c:\Users\Aman Kumar Singh\anaconda3\envs\ats\Lib\site-packages (from arviz<1.0,>=0.13.0->pymc) (26.0)
Requirement already satisfied: xarray>=2023.7.0 in c:\Users\Aman Kumar Singh\anaconda3\envs\ats\Lib\site-packages (from arviz<1.0,>=0.13.0->pymc) (2026.2.0)
Requirement already satisfied: h5netcdf>=1.0.2 in c:\Users\Aman Kumar Singh\anaconda3\envs\ats\Lib\site-packages (from arviz<1.0,>=0.13.0->pymc) (1.8.1)
Requirement already satisfied: h5py in c:\Users\Aman Kumar Singh\anaconda3\envs\ats\Lib\site-packages (from arviz<1.0,>=0.13.0->pymc) (3.16.0)
Requirement already satisfied: xarray-einstats>=0.3 in c:\Users\Aman Kumar Singh\anaconda3\envs\ats\Lib\site-packages (from arviz<1.0,>=0.13.0->pymc) (0.9.1)
Requirement already satisfied: platformdirs in c:\Users\Aman Kumar Singh\anaconda3\envs\ats\Lib\site-packages (from arviz<1.0,>=0.13.0->pymc) (4.9.4)
Requirement already satisfied: llvmlite<0.47,>=0.46.0dev0 in c:\Users\Aman Kumar Singh\anaconda3\envs\ats\Lib\site-packages (from numba<1,>0.57->pytensor) (0.46.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\Users\Aman Kumar Singh\anaconda3\envs\ats\Lib\site-packages (from matplotlib>=3.8->arviz<1.0,>=0.13.0->pymc) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\Users\Aman Kumar Singh\anaconda3\envs\ats\Lib\site-packages (from matplotlib>=3.8->arviz<1.0,>=0.13.0->pymc) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\Users\Aman Kumar Singh\anaconda3\envs\ats\Lib\site-packages (from matplotlib>=3.8->arviz<1.0,>=0.13.0->pymc) (4.62.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\Users\Aman Kumar Singh\anaconda3\envs\ats\Lib\site-packages (from matplotlib>=3.8->arviz<1.0,>=0.13.0->pymc) (1.5.0)
Requirement already satisfied: pillow>=8 in c:\Users\Aman Kumar Singh\anaconda3\envs\ats\Lib\site-packages (from matplotlib>=3.8->arviz<1.0,>=0.13.0->pymc) (10.4.0)
Requirement already satisfied: pyparsing>=3 in c:\Users\Aman Kumar Singh\anaconda3\envs\ats\Lib\site-packages (from matplotlib>=3.8->arviz<1.0,>=0.13.0->pymc) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\Users\Aman Kumar Singh\anaconda3\envs\ats\Lib\site-packages (from matplotlib>=3.8->arviz<1.0,>=0.13.0->pymc) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\Aman Kumar Singh\anaconda3\envs\ats\Lib\site-packages (from pandas>=0.24.0->pymc) (2025.3)
Requirement already satisfied: six>=1.5 in c:\Users\Aman Kumar Singh\anaconda3\envs\ats\Lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.8->arviz<1.0,>=0.13.0->pymc) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\Users\Aman Kumar Singh\anaconda3\envs\ats\Lib\site-packages (from rich>=13.7.1->pymc) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\Users\Aman Kumar Singh\anaconda3\envs\ats\Lib\site-packages (from rich>=13.7.1->pymc) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in c:\Users\Aman Kumar Singh\anaconda3\envs\ats\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.7.1->pymc) (0.1.2)
Requirement already satisfied: toolz in c:\Users\Aman Kumar Singh\anaconda3\envs\ats\Lib\site-packages (from logical-unification->pytensor) (1.1.0)
Requirement already satisfied: multipledispatch in c:\Users\Aman Kumar Singh\anaconda3\envs\ats\Lib\site-packages (from logical-unification->pytensor) (1.0.0)

In [43]:
import pymc as pm
import numpy as np
import pytensor.tensor as pt

WARNING (pytensor.configdefaults): g++ not available, if using conda: `conda install gxx`
WARNING (pytensor.configdefaults): g++ not detected!  PyTensor will be unable to compile C-implementations and will default to Python. Performance may be severely degraded. To remove this warning, set PyTensor flags cxx to an empty string.

In [44]:
df_total = df_long.groupby(["Year_Index", "Age_Index", "Age_Bin", "Year", "Cohort_Index"]).Population.sum().reset_index()

In [ ]:
age_idx = df_total["Age_Index"].values
year_idx = df_total["Year_Index"].values
cohort_idx = df_total["Cohort_Index"].values
pop_obs = df_total["Population"].values

n_ages = df_total["Age_Index"].nunique()
n_cohorts = maxdf_total["Cohort_Index"].nunique()

In [ ]:
pop_scaled = pop_obs / 1000.0
log_offset = np.log(pop_scaled.mean()) 
with pm.Model() as apc_model:
    age_effect = pm.GaussianRandomWalk("age_effect", sigma =0.05, shape = n_ages)
    period_effect = pm.GaussianRandomWalk("period_effect", sigma = 0.05, shape = 3)
    cohort_effect = pm.GaussianRandomWalk("cohort_effect", sigma =0.05, shape = n_cohorts)
    intercept = pm.Normal("intercept", mu = log_offset, sigma = 0.5)
    log_mu = intercept + age_effect[age_idx] + period_effect[year_idx] + cohort_effect[cohort_idx]
    y = pm.Poisson("y", mu=pm.math.exp(log_mu), observed=pop_scaled)
    trace = pm.sample(1000, tune = 1000, target_accept = 0.95, init = "adapt_diag")

In [ ]:
geos = df_long["geography"].unique()
ages = range(n_ages)

forecast_data = []
for g in geos:
    for a in ages:
        forecast_data.append({"geography":g, "Age_Index":a, "Year_Index":2, "Cohort_Index":(2*2)- a +25 })
df_forecast_input = pd.DataFrame(forecast_data)

In [ ]:
with apc_model:
    pm.set_data({"age_idx": df_forecast_input["Age_Index"].values, 
                 "year_idx":df_forecast_input["Year_Index"].values, 
                 "cohort_idx": df_forecast_input["Cohort_Index"].values})
    
    post_pred = pm.sample_posterior_predictive(trace)
    
prediction = post_pred.posterior_predictive["y"].mean(axis=(0,1))
df_forecast_input["Population_2031"] = prediction * 1000

In [ ]:
inv_age_map = {v:k for k,v in age_map.items()}
df_forecast_input["Age_Bin"] = df_forecast_input["Age_Index"].map(inv_age_map)
df_forecast_input[["geography", "Age_Bin", "Population_2031"]].to_csv("forecast_2031_output.csv", index = False)

In [53]:
import pymc as pm
import numpy as np
import pandas as pd

# 1. Aggregate counties to get a National Total
df_total = df_long.groupby(['Year_Index', 'Age_Index', 'Age_Bin', 'Year', 'Cohort_Index']).Population.sum().reset_index()

# 2. Setup Data for Model (Scaling by 1000 for stability)
pop_obs = df_total['Population'].values / 1000.0
age_idx = df_total['Age_Index'].values
year_idx = df_total['Year_Index'].values
cohort_idx = df_total['Cohort_Index'].values

n_ages = df_total['Age_Index'].nunique()
# We calculate n_cohorts based on the max index used in the whole set
n_cohorts = max(df_total['Cohort_Index'].max(), (2*2 - 0 + 25)) + 1 

with pm.Model() as fast_model:
    # Data containers (so we can swap them for forecasting)
    a_in = pm.Data("a_in", age_idx)
    y_in = pm.Data("y_in", year_idx)
    c_in = pm.Data("c_in", cohort_idx)

    # Priors
    alpha = pm.GaussianRandomWalk("age_effect", sigma=0.05, shape=n_ages)
    beta = pm.GaussianRandomWalk("period_effect", sigma=0.05, shape=3) # 2011, 2021, 2031
    gamma = pm.GaussianRandomWalk("cohort_effect", sigma=0.05, shape=n_cohorts)
    intercept = pm.Normal("intercept", mu=np.log(pop_obs.mean()), sigma=0.5)

    # The Formula
    log_mu = intercept + alpha[a_in] + beta[y_in] + gamma[c_in]
    
    # Likelihood
    y_obs = pm.Poisson("y_obs", mu=pm.math.exp(log_mu), observed=pop_obs)

    # Sampling (This will be very fast now!)
    trace = pm.sample(1000, tune=1000, target_accept=0.9)

c:\Users\Aman Kumar Singh\anaconda3\envs\ats\Lib\site-packages\pymc\distributions\timeseries.py:291: UserWarning: Initial distribution not specified, defaulting to `Normal.dist(0, 100)`.You can specify an init_dist manually to suppress this warning.
  warnings.warn(
c:\Users\Aman Kumar Singh\anaconda3\envs\ats\Lib\site-packages\pymc\distributions\timeseries.py:291: UserWarning: Initial distribution not specified, defaulting to `Normal.dist(0, 100)`.You can specify an init_dist manually to suppress this warning.
  warnings.warn(
c:\Users\Aman Kumar Singh\anaconda3\envs\ats\Lib\site-packages\pymc\distributions\timeseries.py:291: UserWarning: Initial distribution not specified, defaulting to `Normal.dist(0, 100)`.You can specify an init_dist manually to suppress this warning.
  warnings.warn(
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (4 chains in 4 jobs)
NUTS: [age_effect, period_effect, cohort_effect, intercept]

Output()

ValueError: Not enough samples to build a trace.